@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class RemarkCommand {
  +COMMAND_WORD: String
  +MESSAGE_USAGE: String
  +MAX_REMARK_LENGTH: int
  +MESSAGE_CONSTRAINTS: String
  +isValidRemark(String): boolean
  +execute(Model): CommandResult
}
Class CommandException

RemarkCommand -up-|> Command
Command ..> CommandException: throws >
RemarkCommand .right.> CommandException: throws >
@enduml
