@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RemarkCommandParser" as RemarkCommandParser LOGIC_COLOR
participant "r:RemarkCommand" as RemarkCommand LOGIC_COLOR
participant "res:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("remark 1 Strong at algorithms")

LogicManager -> AddressBookParser: parseCommand("remark 1 Strong at algorithms")
activate AddressBookParser


AddressBookParser -> RemarkCommandParser : new
activate RemarkCommandParser

AddressBookParser -> RemarkCommandParser : parse("1 Strong at algorithms")

alt invalid index format
    RemarkCommandParser --> AddressBookParser : ParseException
else missing PREFIX_REMARK
    RemarkCommandParser --> AddressBookParser : ParseException
else invalid remark format
    RemarkCommandParser --> AddressBookParser : ParseException
else valid input
    create RemarkCommand
    RemarkCommandParser -> RemarkCommand : new RemarkCommand(index, new Remark("Strong at algorithms"))
    activate RemarkCommand
    deactivate RemarkCommand

    RemarkCommandParser --> AddressBookParser : RemarkCommand
end

deactivate RemarkCommandParser
destroy RemarkCommandParser

AddressBookParser --> LogicManager : RemarkCommand
deactivate AddressBookParser

LogicManager -> RemarkCommand : execute(m)
activate RemarkCommand

RemarkCommand -> Model : getFilteredPersonList()
activate Model
Model --> RemarkCommand : lastShownList
deactivate Model

alt invalid index
    RemarkCommand --> LogicManager : CommandException
else valid index
    RemarkCommand -> Model : setPerson(personToEdit, editedPerson)
    activate Model
    Model --> RemarkCommand
    deactivate Model

    create CommandResult
    alt remark.isEmpty()
        RemarkCommand -> CommandResult : new CommandResult(delete message)
    else !remark.isEmpty()
        RemarkCommand -> CommandResult : new CommandResult(add message)
    end
    activate CommandResult

    CommandResult --> RemarkCommand
    deactivate CommandResult

    RemarkCommand --> LogicManager : CommandResult
end

deactivate RemarkCommand

[<-- LogicManager
deactivate LogicManager
@enduml
